
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdnnxjxgxbhhycfadjuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkbm54anhneGJoaHljZmFkanVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjk0MjMsImV4cCI6MjA1ODk0NTQyM30.5zzz4yJqXx7qZpUMJD0v_uTaYlbhHmAsiBS9n8h4VIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
